name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.29 # Specify the Bun version you want to use
    - shell: bash
      run: bun install
